{
  "comments": [
    {
      "key": {
        "uuid": "121f2602_ccfe2144",
        "filename": "tests/docsisunittest.py",
        "patchSetId": 1
      },
      "lineNbr": 17,
      "author": {
        "id": 1016147
      },
      "writtenOn": "2019-08-13T00:37:59Z",
      "side": 1,
      "message": "Why do we catch this and not just fail?",
      "revId": "b804512a662ebfdf787337fe100433648697004f",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}